spring.application.name=UserService
# 1. H2 Database Configuration
spring.datasource.url=jdbc:h2:mem:ticketdb
spring.datasource.username=Akhil
spring.datasource.password=password

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console


# 2 JPA / Hibernate Properties
spring.jpa.hibernate.ddl-auto=create

server.port=8080
server.servlet.context-path=/user